### ISSUE TITLE
Want annex-B data to FLV converter

### ISSUE THREAD

**Issue by kingsimba** [cohenrotem/pipe_flv2annexb#1]
Do you have some source code to do it? Or can you point me to the right direction? Thanks.

**Comment by cohenrotem** [comment]
All the source code is in the repository, and all the code is public. There is some Python code, and some C++ code.

**Comment by kingsimba** [comment]
I think your project only convert FLV to annex-B, not in the other direction. Do I misunderstand it?

**Comment by cohenrotem** [comment]
You are correct.
The main goal is splitting an H.264 into NAL units in real time style (while encoding the video).
I used FLV because it was the simplest solution I found using FFmpeg command line interface (not the C interface).
It's just a prove of concept (it's not very useful at the current state).
